name: Deploy API Reportfn

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t dijounas/report-gen-api .
      - name: Push image docker
        run: docker push dijounas/report-gen-api

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull dijounas/report-gen-api:latest
      - name: Remove docker container
        run: docker rm -f report-gen-api
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name report-gen-api dijounas/report-gen-api